name: dominion
description: Utilities for domain-driven design
version: 1.0.0-nullsafety.1
repository: https://github.com/netsells/dominion
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dartz: ^0.10.0-nullsafety.1
  meta: ^1.3.0

dev_dependencies:
  effective_dart: ^1.3.0
  test: ^1.16.5
