name: dominion
description: Utilities for domain-driven design
version: 0.1.0
repository: https://github.com/netsells/dominion
environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  dartz: ^0.9.2
  meta: ^1.2.4

dev_dependencies:
  effective_dart: ^1.3.0
  test: ^1.14.4
